name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: false
  group: pages

permissions:
  id-token: write
  pages: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: "web/"

      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
